import Link from "next/link";
import type { Prisma } from "@prisma/client";
import { ArrowRight, CircleDollarSign, Database, Globe2, MapPinned, PhoneCall, ShieldCheck, TrendingUp } from "lucide-react";
import { GenerationButton } from "@/components/generation-button";
import { prisma } from "@/lib/prisma";
import { currencyFormatter, dateFormatter, numberFormatter, statusLabels, websiteStatusLabels } from "@/lib/format";
import { visibleLeadWhere } from "@/lib/leads/blocked-location";
import { getGoogleBusinessUrl } from "@/lib/leads/google-business-url";

const active = visibleLeadWhere({ isActive:true, isFiltered:false, isSuppressed:false, pipelineStage:{is:{slug:{not:"geen-interesse"}}}, websiteStatus:"NO_WEBSITE_CONFIRMED" });
const googleConfirmed = { ...active, googleWebsitePresent:false, googleWebsiteVerifiedAt:{not:null} } satisfies Prisma.LeadWhereInput;
const reviewQueue = visibleLeadWhere({ isFiltered:true, isSuppressed:false, websiteStatus:{in:["NO_WEBSITE_LIKELY","SOCIAL_ONLY","MANUAL_REVIEW_REQUIRED","UNKNOWN"]} });
export default async function DashboardPage() {
  const start=new Date();start.setHours(0,0,0,0);
  const [total,today,likely,social,outdated,broken,review,called,interested,quoted,won,revenue,recent,groups,sources,latestRun]=await Promise.all([
    prisma.lead.count({where:googleConfirmed}),prisma.lead.count({where:{...googleConfirmed,firstDiscoveredAt:{gte:start}}}),
    prisma.lead.count({where:active}),prisma.lead.count({where:{...reviewQueue,websiteStatus:"SOCIAL_ONLY"}}),
    prisma.lead.count({where:visibleLeadWhere({isSuppressed:false,websiteStatus:"WEBSITE_OUTDATED"})}),prisma.lead.count({where:visibleLeadWhere({isSuppressed:false,websiteStatus:"WEBSITE_BROKEN"})}),
    prisma.lead.count({where:reviewQueue}),prisma.lead.count({where:{...active,pipelineStage:{is:{slug:{in:["belletje-1","belletje-2","belletje-3","belletje-4","gemaild"]}}}}}),
    prisma.lead.count({where:{...active,pipelineStage:{is:{slug:"belletje-3"}}}}),prisma.lead.count({where:{...active,pipelineStage:{is:{slug:"belletje-4"}}}}),prisma.lead.count({where:visibleLeadWhere({pipelineStage:{is:{slug:"deal"}}})}),
    prisma.lead.aggregate({where:visibleLeadWhere(),_sum:{expectedRevenueCents:true,wonRevenueCents:true}}),
    prisma.lead.findMany({where:active,orderBy:[{opportunityScore:"desc"},{firstDiscoveredAt:"desc"}],take:7}),
    prisma.lead.groupBy({by:["category"],where:active,_count:{id:true},orderBy:{_count:{category:"desc"}},take:6}),
    prisma.lead.groupBy({by:["source"],where:active,_count:{id:true},orderBy:{_count:{source:"desc"}},take:5}),
    prisma.generationRun.findFirst({orderBy:{createdAt:"desc"}}),
  ]);
  const max=Math.max(1,...groups.map((group)=>group._count.id));
  return <div className="content"><header className="page-head"><div><span className="eyebrow">Actueel overzicht</span><h1>Dashboard</h1><p className="muted">Permanente clouddata met uitlegbare websiteclassificatie en gratis bronnen.</p></div><div className="actions"><GenerationButton/><Link className="button button-secondary" href="/leads">Bekijk alle leads <ArrowRight size={15}/></Link></div></header>
    <section className="stats"><Stat icon={<Database size={18}/>} label="Google-bevestigde leads" value={total} meta={`${today} vandaag`}/><Stat icon={<Globe2 size={18}/>} label="Geen website bevestigd" value={likely} meta={`${Math.max(0,likely-total)} nog Google-controle aanbevolen`}/><Stat icon={<MapPinned size={18}/>} label="Social-only te controleren" value={social} meta="Niet actief vóór Google-controle"/><Stat icon={<ShieldCheck size={18}/>} label="Handmatige controle" value={review} meta="Onzeker staat nooit tussen leads"/><Stat icon={<TrendingUp size={18}/>} label="Verouderd / kapot" value={outdated+broken} meta={`${broken} technisch kapot`}/><Stat icon={<PhoneCall size={18}/>} label="Opgevolgd" value={called} meta={`${interested} bij Belletje 3`}/><Stat icon={<CircleDollarSign size={18}/>} label="Belletje 4" value={quoted} meta={`${won} deals`}/><Stat label="Verwachte omzet" value={currencyFormatter.format((revenue._sum.expectedRevenueCents??0)/100)} meta={`Deals ${currencyFormatter.format((revenue._sum.wonRevenueCents??0)/100)}`}/></section>
    {latestRun&&<section className="card card-pad run-summary"><div><h2>Laatste lokale zoekrun</h2><p className="small muted">{latestRun.createdAt.toLocaleString("nl-NL")} · {statusLabels[latestRun.status]} · {latestRun.stopReason||"Nog bezig"}</p></div><div className="run-summary-metrics"><span><strong>{latestRun.stored}</strong> bevestigd</span><span><strong>{latestRun.manualReview}</strong> in retryqueue</span><span><strong>{latestRun.duplicates}</strong> duplicaten</span><span><strong>{latestRun.sourceFailures}</strong> bronfouten</span></div></section>}
    <div className="grid-two"><section className="card"><div className="card-pad"><h2>Beste nieuwe kansen</h2><p className="small muted">Direct belbare, actieve bedrijven zonder bevestigde eigen website.</p></div>{recent.length?<div className="table-scroll"><table><thead><tr><th>Bedrijf</th><th>Telefoon</th><th>Adres</th><th>Plaats</th><th>Website</th><th>Gevonden</th></tr></thead><tbody>{recent.map((lead)=><tr key={lead.id}><td><Link className="company" href={`/leads/${lead.id}`}>{lead.companyName}</Link></td><td>{lead.normalizedPhoneNumber||lead.phoneNumber?<a className="text-link" href={`tel:${lead.normalizedPhoneNumber||lead.phoneNumber}`}>{lead.normalizedPhoneNumber||lead.phoneNumber}</a>:"Niet beschikbaar"}</td><td><a className="text-link" href={getGoogleBusinessUrl(lead)} target="_blank" rel="noopener noreferrer">{lead.formattedAddress||lead.streetAddress}</a></td><td>{lead.city}, {lead.country}</td><td><span className="badge">{websiteStatusLabels[lead.websiteStatus]}</span></td><td>{dateFormatter.format(lead.firstDiscoveredAt)}</td></tr>)}</tbody></table></div>:<Empty/>}</section><section className="card card-pad"><h2>Leads per branche</h2><div className="bars" style={{marginTop:20}}>{groups.map((group)=><div className="bar-row" key={group.category}><span>{group.category.replaceAll("_"," ")}</span><div className="progress"><span style={{width:`${group._count.id/max*100}%`}}/></div><strong>{group._count.id}</strong></div>)}</div><h2 style={{marginTop:28}}>Bronnen</h2><div className="source-list">{sources.map((source)=><span key={source.source}><b>{statusLabels[source.source]}</b><strong>{source._count.id}</strong></span>)}</div></section></div></div>;
}
function Stat({icon,label,value,meta}:{icon?:React.ReactNode;label:string;value:number|string;meta:string}){return <div className="card stat"><div className="stat-head"><span className="stat-label">{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{typeof value==="number"?numberFormatter.format(value):value}</div><div className="stat-meta">{meta}</div></div>;}
function Empty(){return <div className="empty"><strong>Nog geen leads</strong><span>Start een lokale zoekrun om het overzicht te vullen.</span></div>;}
