import "server-only";
import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { reserveApiCall } from "@/lib/jobs/quota";
import { scoreWebsite } from "./score";

export type WebsiteAnalysisResult = { websiteUrl:string; opportunityScore:number; mobileScore:number|null; desktopScore:number|null; conversionQualityScore:number; isReachable:boolean; isMobileFriendly:boolean|null; hasContactForm:boolean|null; hasClearCta:boolean|null; hasBrokenLinks:boolean|null; brokenLinkCount:number; hasViewportMeta:boolean|null; hasOutdatedCopyright:boolean|null; hasPlaceholderContent:boolean|null; loadTimeMs:number|null; reasons:{code:string;label:string;weight:number}[]; rawSignals:Record<string,unknown> };

function privateAddress(address:string){return /^(127\.|10\.|0\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.|::1$|fc|fd|fe80)/i.test(address)}
export async function assertPublicUrl(value:string){const url=new URL(value);if(!["http:","https:"].includes(url.protocol)||url.username||url.password)throw new Error("Ongeldige website-URL");if(url.hostname==="localhost")throw new Error("Lokale adressen zijn niet toegestaan");const records=await lookup(url.hostname,{all:true});if(!records.length||records.some(r=>privateAddress(r.address)||!isIP(r.address)))throw new Error("Privé-adressen zijn niet toegestaan");return url}

async function safeFetch(urlValue:string, init:RequestInit={}){let url=await assertPublicUrl(urlValue);for(let redirect=0;redirect<4;redirect+=1){const response=await fetch(url,{...init,redirect:"manual",signal:AbortSignal.timeout(12_000),headers:{"User-Agent":"LeadfinderSitora/1.0 website-quality-check",...(init.headers||{})}});if(response.status>=300&&response.status<400&&response.headers.get("location")){url=await assertPublicUrl(new URL(response.headers.get("location")!,url).toString());continue}return response}throw new Error("Te veel redirects")}

type Psi={lighthouseResult?:{categories?:{performance?:{score?:number}};audits?:Record<string,{score?:number|null;numericValue?:number}>;runtimeError?:unknown}};
async function pagespeed(url:string,strategy:"mobile"|"desktop",apiKey:string,limit:number){await reserveApiCall(limit,"PAGESPEED");const endpoint=new URL("https://pagespeedonline.googleapis.com/pagespeedonline/v5/runPagespeed");endpoint.searchParams.set("url",url);endpoint.searchParams.set("strategy",strategy);for(const category of ["performance","best-practices","seo","accessibility"])endpoint.searchParams.append("category",category);endpoint.searchParams.set("key",apiKey);const response=await fetch(endpoint,{signal:AbortSignal.timeout(90_000),cache:"no-store"});if(!response.ok)throw new Error(`PageSpeed-fout (${response.status})`);return response.json() as Promise<Psi>}

export async function analyzeWebsite(websiteUrl:string):Promise<WebsiteAnalysisResult>{const url=(await assertPublicUrl(websiteUrl)).toString();const key=process.env.PAGESPEED_API_KEY;const limit=Number(process.env.PAGESPEED_DAILY_LIMIT??25);let html="";let reachable=true;let loadTimeMs:number|null=null;let brokenLinkCount=0;const started=Date.now();try{const response=await safeFetch(url);loadTimeMs=Date.now()-started;reachable=response.ok;html=(await response.text()).slice(0,1_500_000)}catch{reachable=false}
  const lower=html.toLowerCase();const viewport=html?/<meta[^>]+name=["']viewport["']/i.test(html):null;const cta=html?/(offerte|afspraak|contact|bel ons|boek nu|reserveer|vraag aan)/i.test(lower):null;const form=html?/<form[\s>]/i.test(html):null;const placeholder=html?/(coming soon|under construction|binnenkort beschikbaar|website in aanbouw)/i.test(lower):null;const years=[...lower.matchAll(/(?:©|copyright)[^\d]{0,20}(20\d{2})/g)].map(m=>Number(m[1]));const outdatedCopyright=years.length?Math.max(...years)<new Date().getFullYear()-2:null;
  if(html){const origin=new URL(url).origin;const links=[...html.matchAll(/href=["']([^"'#]+)["']/gi)].map(m=>{try{return new URL(m[1],url)}catch{return null}}).filter((v):v is URL=>!!v&&v.origin===origin).slice(0,5);for(const link of links){try{const r=await safeFetch(link.toString(),{method:"HEAD"});if(r.status>=400)brokenLinkCount+=1}catch{brokenLinkCount+=1}}}
  let mobileScore:number|null=null,desktopScore:number|null=null,psiMobile:Psi|null=null;if(key&&reachable){try{const [mobile,desktop]=await Promise.all([pagespeed(url,"mobile",key,limit),pagespeed(url,"desktop",key,limit)]);psiMobile=mobile;mobileScore=Math.round((mobile.lighthouseResult?.categories?.performance?.score??0)*100);desktopScore=Math.round((desktop.lighthouseResult?.categories?.performance?.score??0)*100)}catch{/* HTML-signalen blijven bruikbaar */}}
  const scores=scoreWebsite({reachable,mobileScore,desktopScore,viewport,cta,form,placeholder,outdatedCopyright,brokenLinks:brokenLinkCount,loadTimeMs});return {websiteUrl:url,...scores,mobileScore,desktopScore,isReachable:reachable,isMobileFriendly:viewport,hasContactForm:form,hasClearCta:cta,hasBrokenLinks:html?brokenLinkCount>0:null,brokenLinkCount,hasViewportMeta:viewport,hasOutdatedCopyright:outdatedCopyright,hasPlaceholderContent:placeholder,loadTimeMs,reasons:scores.reasons,rawSignals:{lighthouseRuntimeError:psiMobile?.lighthouseResult?.runtimeError??null,checkedLinks:html?Math.min(5,[...html.matchAll(/href=/gi)].length):0}}}
