"use client";
import { createContext,useContext,useEffect,useMemo,useState } from "react";
import type { ExportRecord,Lead,LeadStatus,SearchInput } from "@/types/lead";
import { LEAD_STATUSES } from "@/types/lead";
import { demoLeads } from "@/lib/demo/leads";

type StoredSearch={id:string;query:string;city:string;count:number;date:string;provider:string;saved?:boolean};
type Store={leads:Lead[];savedIds:string[];selectedIds:string[];searches:StoredSearch[];exports:ExportRecord[];ready:boolean;setResults:(l:Lead[],q:SearchInput,p:string)=>void;saveSearch:(q:SearchInput)=>void;toggleSelected:(id:string)=>void;selectMany:(ids:string[])=>void;clearSelection:()=>void;toggleSave:(id:string)=>void;saveMany:(ids:string[])=>void;removeSaved:(id:string)=>void;deleteLeads:(ids:string[])=>void;setStatus:(ids:string[],s:LeadStatus)=>void;addTag:(ids:string[],t:string)=>void;updateLead:(id:string,p:Partial<Lead>)=>void;recordExport:(format:ExportRecord["format"],count:number,fileName:string)=>void;resetData:()=>void};
const C=createContext<Store|null>(null);const KEY="sitora-leadfinder-state-v2";
const normalizeStatus=(status:string):LeadStatus=>LEAD_STATUSES.includes(status as LeadStatus)?status as LeadStatus:status==="Geïnteresseerd"?"Interessant":status==="Klant"?"Klant geworden":status==="Niet relevant"?"Niet interessant":"Nieuw";
const initialSearches:StoredSearch[]=[{id:"s1",query:"Bouw & klus",city:"Amsterdam",count:4,date:new Date().toISOString(),provider:"demo"},{id:"s2",query:"Horeca",city:"Rotterdam",count:4,date:new Date(Date.now()-86400000).toISOString(),provider:"demo"}];

export function AppStore({children}:{children:React.ReactNode}){const[ready,setReady]=useState(false);const[leads,setLeads]=useState<Lead[]>(demoLeads);const[savedIds,setSavedIds]=useState<string[]>(demoLeads.slice(0,7).map(l=>l.id));const[selectedIds,setSelectedIds]=useState<string[]>([]);const[searches,setSearches]=useState<StoredSearch[]>(initialSearches);const[exports,setExports]=useState<ExportRecord[]>([]);
useEffect(()=>{const raw=localStorage.getItem(KEY)||localStorage.getItem("sitora-demo-state-v1");if(raw){try{const s=JSON.parse(raw);setLeads((s.leads||demoLeads).map((l:Lead)=>({...l,status:normalizeStatus(l.status)})));setSavedIds(s.savedIds||[]);setSelectedIds(s.selectedIds||[]);setSearches(s.searches||initialSearches);setExports(s.exports||[]);}catch{}}setReady(true)},[]);
useEffect(()=>{if(ready)localStorage.setItem(KEY,JSON.stringify({leads,savedIds,selectedIds,searches,exports}))},[ready,leads,savedIds,selectedIds,searches,exports]);
const value=useMemo<Store>(()=>({leads,savedIds,selectedIds,searches,exports,ready,setResults:(newLeads,q,p)=>{setLeads(prev=>[...newLeads,...prev.filter(x=>!newLeads.some(n=>n.id===x.id))]);setSearches(x=>[{id:crypto.randomUUID(),query:q.branch||q.query||q.companyName||"Zoekopdracht",city:q.city||q.province||"Heel Nederland",count:newLeads.length,date:new Date().toISOString(),provider:p},...x].slice(0,20));sessionStorage.setItem("sitora-result-ids",JSON.stringify(newLeads.map(l=>l.id)));},saveSearch:q=>setSearches(x=>[{id:crypto.randomUUID(),query:q.branch||q.query||q.companyName||"Zoekopdracht",city:q.city||q.province||"Heel Nederland",count:0,date:new Date().toISOString(),provider:"opgeslagen",saved:true},...x].slice(0,20)),toggleSelected:id=>setSelectedIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]),selectMany:ids=>setSelectedIds(x=>Array.from(new Set([...x,...ids]))),clearSelection:()=>setSelectedIds([]),toggleSave:id=>setSavedIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]),saveMany:ids=>setSavedIds(x=>Array.from(new Set([...x,...ids]))),removeSaved:id=>setSavedIds(x=>x.filter(v=>v!==id)),deleteLeads:ids=>{setLeads(x=>x.filter(l=>!ids.includes(l.id)));setSavedIds(x=>x.filter(id=>!ids.includes(id)));setSelectedIds(x=>x.filter(id=>!ids.includes(id)))},setStatus:(ids,status)=>setLeads(x=>x.map(l=>ids.includes(l.id)?{...l,status,contactedAt:status==="Benaderd"?new Date().toISOString():l.contactedAt}:l)),addTag:(ids,t)=>setLeads(x=>x.map(l=>ids.includes(l.id)?{...l,tags:Array.from(new Set([...l.tags,t]))}:l)),updateLead:(id,p)=>setLeads(x=>x.map(l=>l.id===id?{...l,...p}:l)),recordExport:(format,count,fileName)=>setExports(x=>[{id:crypto.randomUUID(),format,count,fileName,createdAt:new Date().toISOString()},...x].slice(0,50)),resetData:()=>{setLeads(demoLeads);setSavedIds([]);setSelectedIds([]);setSearches(initialSearches);setExports([]);localStorage.removeItem(KEY);}}),[leads,savedIds,selectedIds,searches,exports,ready]);return <C.Provider value={value}>{children}</C.Provider>}
export function useAppStore(){const value=useContext(C);if(!value)throw new Error("AppStore ontbreekt");return value;}
