"use client";
import React from "react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Activity, ExternalLink, LoaderCircle, Save, ShieldCheck, Trash2 } from "lucide-react";
import { pipelineStatuses, pipelineStatusLabels } from "@/lib/leads/pipeline";

export function LeadEditor({leadId,status,notes,filterReason}:{leadId:string;status:string;notes:string;filterReason?:string|null}){const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch(`/api/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:form.get("status"),notes:form.get("notes"),filterReason:form.get("filterReason")})});setPending(false);setMessage(response.ok?"Wijzigingen opgeslagen":"Opslaan mislukt");if(response.ok)router.refresh()}return <form onSubmit={submit} className="card card-pad"><h2>Opvolging</h2><div className="form-stack" style={{marginTop:16}}><div className="field"><label htmlFor="status">Pipelinefase</label><select className="select" id="status" name="status" defaultValue={status}>{pipelineStatuses.map(item=><option value={item} key={item}>{pipelineStatusLabels[item]}</option>)}</select></div><div className="field"><label htmlFor="filterReason">Interne reden</label><input className="input" id="filterReason" name="filterReason" defaultValue={filterReason||""} placeholder="Optionele interne toelichting"/></div><div className="field"><label htmlFor="notes">Notities</label><textarea className="textarea" id="notes" name="notes" defaultValue={notes} placeholder="Voeg interne verkoopnotities toe…"/></div><button className="button button-primary" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={16}/>:<Save size={15}/>}Opslaan</button>{message&&<span className="small muted" aria-live="polite">{message}</span>}</div></form>}

export function AnalyzeButton({leadId,disabled}:{leadId:string;disabled:boolean}){const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function analyze(){setPending(true);const response=await fetch(`/api/leads/${leadId}/analyze`,{method:"POST"});const data=await response.json();setPending(false);setMessage(response.ok?"Analyse is ingepland":data.error||"Inplannen mislukt")}return <div><button className="button button-secondary" onClick={analyze} disabled={disabled||pending}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<Activity size={15}/>}Website opnieuw analyseren</button>{message&&<p className="small muted" style={{marginTop:8}}>{message}</p>}</div>}

export function QuickStatus({leadId,status}:{leadId:string;status:string}){const router=useRouter();const[pending,setPending]=useState(false);async function change(value:string){setPending(true);await fetch(`/api/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})});setPending(false);router.refresh()}return <select className="select" aria-label="Pipelinefase" value={status} onChange={e=>change(e.target.value)} disabled={pending} style={{minWidth:145}}>{pipelineStatuses.map(item=><option value={item} key={item}>{pipelineStatusLabels[item]}</option>)}</select>}

export function SuppressLeadButton({leadId}:{leadId:string}){const router=useRouter();const[pending,setPending]=useState(false);async function suppress(){if(!window.confirm("Deze lead verwijderen en blokkeren voor toekomstige imports?"))return;setPending(true);const response=await fetch(`/api/leads/${leadId}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Handmatig verwijderd; niet opnieuw importeren"})});if(response.ok){router.push("/leads");router.refresh()}else setPending(false)}return <button className="button button-danger" onClick={suppress} disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<Trash2 size={15}/>}Verwijderen en blokkeren</button>}

export function WebsiteReviewActions({leadId,googleUrl,currentWebsite}:{leadId:string;googleUrl:string;currentWebsite?:string|null}){
  const router=useRouter();const[pending,setPending]=useState(false);const[websiteUrl,setWebsiteUrl]=useState(currentWebsite||"");const[message,setMessage]=useState("");
  async function review(websiteReview:"NO_WEBSITE_CONFIRMED"|"WEBSITE_FOUND"){
    if(websiteReview==="NO_WEBSITE_CONFIRMED"&&!window.confirm("Heb je het actuele Google-bedrijfsprofiel geopend en gecontroleerd dat daar geen websiteknop of eigen domein staat?"))return;
    if(websiteReview==="WEBSITE_FOUND"&&!websiteUrl.trim()){setMessage("Vul eerst de gevonden eigen website in.");return;}
    setPending(true);setMessage("");
    const response=await fetch(`/api/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({websiteReview,websiteUrl})});
    const data=await response.json().catch(()=>({}));setPending(false);setMessage(response.ok?"Websitecontrole opgeslagen":data.error||"Opslaan mislukt");if(response.ok)router.refresh();
  }
  return <section className="card card-pad"><h2>Verplichte Google-controle</h2><p className="small muted">Open eerst het actuele bedrijfsprofiel. Alleen een handmatig bevestigde afwezigheid wordt een actieve lead.</p><div className="form-stack" style={{marginTop:14}}><a className="button button-secondary" href={googleUrl} target="_blank" rel="noopener noreferrer">Google-bedrijfsprofiel openen <ExternalLink size={14}/></a><div className="field"><label htmlFor="reviewWebsiteUrl">Eigen website gevonden</label><input className="input" id="reviewWebsiteUrl" value={websiteUrl} onChange={event=>setWebsiteUrl(event.target.value)} placeholder="https://bedrijfsnaam.nl"/></div><button type="button" className="button button-secondary" disabled={pending} onClick={()=>review("WEBSITE_FOUND")}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<ExternalLink size={15}/>}Website gevonden: uitsluiten</button><button type="button" className="button button-primary" disabled={pending} onClick={()=>review("NO_WEBSITE_CONFIRMED")}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<ShieldCheck size={15}/>}Google gecontroleerd: geen website</button>{message&&<span className="small muted" aria-live="polite">{message}</span>}</div></section>;
}
