"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { Activity, LoaderCircle, Save, Trash2 } from "lucide-react";
import { leadStatuses } from "@/lib/leads/filters";
import { statusLabels } from "@/lib/format";

export function LeadEditor({leadId,status,notes,filterReason}:{leadId:string;status:string;notes:string;filterReason?:string|null}){const router=useRouter();const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage("");const form=new FormData(event.currentTarget);const response=await fetch(`/api/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:form.get("status"),notes:form.get("notes"),filterReason:form.get("filterReason")})});setPending(false);setMessage(response.ok?"Wijzigingen opgeslagen":"Opslaan mislukt");if(response.ok)router.refresh()}return <form onSubmit={submit} className="card card-pad"><h2>Opvolging</h2><div className="form-stack" style={{marginTop:16}}><div className="field"><label htmlFor="status">Leadstatus</label><select className="select" id="status" name="status" defaultValue={status}>{leadStatuses.map(item=><option value={item} key={item}>{statusLabels[item]}</option>)}</select></div><div className="field"><label htmlFor="filterReason">Reden filtering</label><input className="input" id="filterReason" name="filterReason" defaultValue={filterReason||""} placeholder="Alleen nodig bij Gefilterd"/></div><div className="field"><label htmlFor="notes">Notities</label><textarea className="textarea" id="notes" name="notes" defaultValue={notes} placeholder="Voeg interne verkoopnotities toe…"/></div><button className="button button-primary" disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={16}/>:<Save size={15}/>}Opslaan</button>{message&&<span className="small muted" aria-live="polite">{message}</span>}</div></form>}

export function AnalyzeButton({leadId,disabled}:{leadId:string;disabled:boolean}){const[pending,setPending]=useState(false);const[message,setMessage]=useState("");async function analyze(){setPending(true);const response=await fetch(`/api/leads/${leadId}/analyze`,{method:"POST"});const data=await response.json();setPending(false);setMessage(response.ok?"Analyse is ingepland":data.error||"Inplannen mislukt")}return <div><button className="button button-secondary" onClick={analyze} disabled={disabled||pending}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<Activity size={15}/>}Website opnieuw analyseren</button>{message&&<p className="small muted" style={{marginTop:8}}>{message}</p>}</div>}

export function QuickStatus({leadId,status}:{leadId:string;status:string}){const router=useRouter();const[pending,setPending]=useState(false);async function change(value:string){setPending(true);await fetch(`/api/leads/${leadId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:value})});setPending(false);router.refresh()}return <select className="select" aria-label="Leadstatus" value={status} onChange={e=>change(e.target.value)} disabled={pending} style={{minWidth:145}}>{leadStatuses.map(item=><option value={item} key={item}>{statusLabels[item]}</option>)}</select>}

export function SuppressLeadButton({leadId}:{leadId:string}){const router=useRouter();const[pending,setPending]=useState(false);async function suppress(){if(!window.confirm("Deze lead verwijderen en blokkeren voor toekomstige imports?"))return;setPending(true);const response=await fetch(`/api/leads/${leadId}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:"Handmatig verwijderd; niet opnieuw importeren"})});if(response.ok){router.push("/leads");router.refresh()}else setPending(false)}return <button className="button button-danger" onClick={suppress} disabled={pending}>{pending?<LoaderCircle className="animate-spin" size={15}/>:<Trash2 size={15}/>}Verwijderen en blokkeren</button>}
