import { AlertTriangle, Database, HardDrive, ServerCog, ShieldCheck } from "lucide-react";
import { requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { numberFormatter, statusLabels } from "@/lib/format";
import { RetryJobButton } from "@/components/admin-actions";
import { CategoryManager } from "@/components/category-manager";
import { CoveragePriorityManager } from "@/components/coverage-priority-manager";
import { visibleLeadWhere } from "@/lib/leads/blocked-location";

export default async function AdminPage(){await requireRole("ADMIN");const[jobs,coverage,categories,excluded,sourceRecords,exclusions,unknown,filtered,runs,retryQueue,pipelineAudit,pipelineStages,cleanupAudit]=await Promise.all([
  prisma.scanJob.findMany({orderBy:{createdAt:"desc"},take:25,include:{coverageArea:true}}),prisma.coverageArea.groupBy({by:["country","status"],_count:{id:true},orderBy:{country:"asc"}}),
  prisma.category.findMany({orderBy:[{isActive:"desc"},{name:"asc"}]}),prisma.excludedCategory.findMany({orderBy:[{isActive:"desc"},{name:"asc"}]}),
  prisma.sourceRecord.count(),prisma.leadExclusion.count(),prisma.lead.count({where:visibleLeadWhere({websiteStatus:{in:["UNKNOWN","MANUAL_REVIEW_REQUIRED","SOCIAL_ONLY","NO_WEBSITE_LIKELY"]}})}),prisma.lead.count({where:visibleLeadWhere({isFiltered:true})}),
  prisma.generationRun.findMany({orderBy:{createdAt:"desc"},take:10,include:{logs:{orderBy:{createdAt:"desc"},take:3}}}),prisma.validationCandidate.groupBy({by:["status"],_count:{id:true}}),
  prisma.pipelineMigrationAudit.findFirst({orderBy:{createdAt:"desc"}}),prisma.pipelineStage.findMany({where:{isActive:true},orderBy:{position:"asc"},include:{_count:{select:{leads:true}}}}),prisma.blockedLocationCleanupAudit.findFirst({orderBy:{createdAt:"desc"}}),]);
  const metric=(country:string)=>{const rows=coverage.filter((row)=>row.country===country);const total=rows.reduce((sum,row)=>sum+row._count.id,0);const scanned=rows.reduce((sum,row)=>sum+(row.status!=="PENDING"?row._count.id:0),0);return{total,done:scanned,pct:total?Math.round(scanned/total*100):0};};
  const activeJobs=jobs.filter((job)=>job.status==="RUNNING").length;const failed=jobs.filter((job)=>job.status==="FAILED").length;const retryPending=retryQueue.filter((row)=>["PENDING_VALIDATION","RETRY_REQUIRED","RETRY_SCHEDULED","VALIDATING"].includes(row.status)).reduce((sum,row)=>sum+row._count.id,0);
  return <div className="content"><header className="page-head"><div><span className="eyebrow">Lokaal beheer</span><h1>Bronnen & datakwaliteit</h1><p className="muted">Gratis bronnen, zoekruns, uitsluitingen en lokale opslag.</p></div><span className="badge badge-green"><ShieldCheck size={13}/>Geen betaalde API actief</span></header>
    <section className="stats"><Metric icon={<ServerCog size={18}/>} label="Actieve jobs" value={activeJobs} meta={`${failed} mislukt`}/><Metric icon={<Database size={18}/>} label="Bronrecords" value={sourceRecords} meta="Met ophaaldatum"/><Metric icon={<HardDrive size={18}/>} label="Retryqueue" value={retryPending} meta={`${unknown} bestaande handmatige controles`}/><Metric icon={<AlertTriangle size={18}/>} label="Gefilterd" value={filtered} meta={`${exclusions} duurzame uitsluitingen`}/></section>
    {pipelineAudit&&<section className="card card-pad admin-section" data-testid="pipeline-migration-audit"><h2>Pipeline-migratiecontrole</h2><p><strong>{pipelineAudit.totalBefore}</strong> leads vóór · <strong>{pipelineAudit.totalAfter}</strong> leads na · <strong>{pipelineAudit.migratedLeads}</strong> gemigreerd · <strong>{pipelineAudit.unknownStages}</strong> onbekende fases</p><div className="grid-two"><div><h3>Oude verdeling</h3><p className="small muted">{distributionText(pipelineAudit.distributionBefore)}</p></div><div><h3>Nieuwe verdeling</h3><p className="small muted">{distributionText(pipelineAudit.distributionAfter)}</p></div></div><p className="small muted">Actieve fases uit PostgreSQL: {pipelineStages.map(stage=>`${stage.position}. ${stage.name} (${stage._count.leads})`).join(" · ")}</p></section>}
    {cleanupAudit&&<section className="card card-pad admin-section" data-testid="blocked-location-cleanup-audit"><h2>Opschoning Brussel en Gent</h2><p><strong>{cleanupAudit.totalChecked}</strong> gecontroleerd · <strong>{cleanupAudit.brusselsFound}</strong> Brussel · <strong>{cleanupAudit.ghentFound}</strong> Gent · <strong>{cleanupAudit.removed}</strong> veilig verwijderd</p><p className="small muted">Run-ID: {cleanupAudit.id} · herstelkopie: {cleanupAudit.backupTable} · {cleanupAudit.createdAt.toLocaleString("nl-NL")}</p></section>}
    <div className="grid-two"><section className="card card-pad"><h2>Zoekdekking</h2><Coverage label="Nederland" data={metric("NL")}/><Coverage label="België" data={metric("BE")}/><hr/><p className="small muted">Een bronfout stopt de volledige run niet. Overpass-fallbacks, retries, time-outs en harde requestlimieten zijn actief.</p></section><section className="card card-pad"><h2>Cloudopslag</h2><p>PostgreSQL bewaart leads, bewijs, activiteiten, filters en notities permanent buiten de applicatieserver.</p><p className="small muted">Databasemigraties worden gecontroleerd uitgevoerd tijdens een deployment.</p></section></div>
    <CategoryManager categories={categories} excluded={excluded}/><CoveragePriorityManager/><section className="card table-card admin-section"><div className="card-pad"><h2>Recente zoekruns</h2></div><div className="table-scroll"><table><thead><tr><th>Status</th><th>Fase</th><th>Regio</th><th>Gevonden</th><th>Gecontroleerd</th><th>Opgeslagen</th><th>Duplicaten</th><th>Bronfouten</th><th>Stopreden</th></tr></thead><tbody>{runs.map((run)=><tr key={run.id}><td><span className="badge">{statusLabels[run.status]}</span></td><td>{run.currentPhase}</td><td>{run.currentRegion||"—"}</td><td>{run.candidatesFound}</td><td>{run.candidatesChecked}</td><td>{run.stored}/{run.targetCount}</td><td>{run.duplicates}</td><td title={run.logs.map((log)=>log.message).join("\n")}>{run.sourceFailures}</td><td className="small">{run.stopReason||"—"}</td></tr>)}</tbody></table></div></section>
    <section className="card table-card admin-section"><div className="card-pad"><h2>Recente scanjobs</h2></div>{jobs.length?<div className="table-scroll"><table><thead><tr><th>Type</th><th>Gebied / lead</th><th>Status</th><th>Gevonden</th><th>Opgeslagen</th><th>Gestart</th><th>Fout</th><th></th></tr></thead><tbody>{jobs.map((job)=><tr key={job.id}><td>{job.type}</td><td>{job.coverageArea?.city||job.leadId||"—"}</td><td><span className="badge">{statusLabels[job.status]}</span></td><td>{job.recordsFound}</td><td>{job.recordsStored}</td><td>{job.startedAt?.toLocaleString("nl-NL")||"—"}</td><td className="small">{job.errorMessage||"—"}</td><td>{job.status==="FAILED"&&<RetryJobButton id={job.id}/>}</td></tr>)}</tbody></table></div>:<div className="empty"><strong>Nog geen jobs</strong></div>}</section></div>;
}
function Metric({icon,label,value,meta}:{icon?:React.ReactNode;label:string;value:number;meta:string}){return <div className="card stat"><div className="stat-head"><span className="stat-label">{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{numberFormatter.format(value)}</div><div className="stat-meta">{meta}</div></div>;}
function Coverage({label,data}:{label:string;data:{total:number;done:number;pct:number}}){return <div className="coverage"><div><strong>{label}</strong><span className="muted">{data.done} / {data.total} · {data.pct}%</span></div><div className="progress"><span style={{width:`${data.pct}%`}}/></div></div>;}
function distributionText(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return"Geen rapport beschikbaar";return Object.entries(value).map(([name,count])=>`${name}: ${String(count)}`).join(" · ");}
