import { AlertTriangle, CheckCircle2, Gauge, ServerCog } from "lucide-react";
import { requireRole } from "@/lib/auth/session";
import { prisma } from "@/lib/prisma";
import { numberFormatter, statusLabels } from "@/lib/format";
import { RetryJobButton } from "@/components/admin-actions";
import { CategoryManager } from "@/components/category-manager";

export default async function AdminPage() {
  await requireRole("ADMIN");
  const now = new Date(); const today = now.toISOString().slice(0, 10); const monthPrefix = today.slice(0, 7);
  const [usage, jobs, coverage, categories, excluded, noWebsite, websiteOpportunities, filtered, runs] = await Promise.all([
    prisma.apiUsage.findMany({ where: { dateKey: { startsWith: monthPrefix } } }), prisma.scanJob.findMany({ orderBy: { createdAt: "desc" }, take: 25, include: { coverageArea: true } }),
    prisma.coverageArea.groupBy({ by: ["country", "status"], _count: { id: true }, orderBy: { country: "asc" } }), prisma.category.findMany({ orderBy: [{ isActive: "desc" }, { name: "asc" }] }),
    prisma.excludedCategory.findMany({ orderBy: [{ isActive: "desc" }, { name: "asc" }] }), prisma.lead.count({ where: { leadType: "NO_WEBSITE", isActive: true } }),
    prisma.lead.count({ where: { leadType: { in: ["OUTDATED_WEBSITE", "IMPROVABLE_WEBSITE"] }, isActive: true } }), prisma.lead.count({ where: { isFiltered: true } }),
    prisma.generationRun.findMany({ orderBy: { createdAt: "desc" }, take: 10, include: { logs: { orderBy: { createdAt: "desc" }, take: 3 } } }),
  ]);
  const calls = (provider: string, onlyToday = false) => usage.filter((row) => row.provider === provider && (!onlyToday || row.dateKey === today)).reduce((sum, row) => sum + row.calls, 0);
  const googleToday = calls("GOOGLE_PLACES", true), googleMonth = calls("GOOGLE_PLACES"), pagespeedToday = calls("PAGESPEED", true);
  const dailyLimit = Number(process.env.GOOGLE_PLACES_DAILY_LIMIT ?? 250), monthlyLimit = Number(process.env.GOOGLE_PLACES_MONTHLY_LIMIT ?? 1000);
  const paidEnabled = process.env.PAID_PROVIDERS_ENABLED === "true";
  const metric = (country: string) => { const rows = coverage.filter((row) => row.country === country); const total = rows.reduce((sum, row) => sum + row._count.id, 0); const done = rows.filter((row) => row.status === "COMPLETE").reduce((sum, row) => sum + row._count.id, 0); return { total, done, pct: total ? Math.round(done / total * 100) : 0 }; };
  const nl = metric("NL"), be = metric("BE"); const activeJobs = jobs.filter((job) => job.status === "RUNNING").length; const failed = jobs.filter((job) => job.status === "FAILED").length;
  return <div className="content">
    <header className="page-head"><div><span className="eyebrow">Beveiligd beheer</span><h1>Scans & kwaliteit</h1><p className="muted">Dekking, bronbudget, websiteanalyses en categorieën.</p></div><span className={`badge ${paidEnabled ? "badge-amber" : "badge-green"}`}><CheckCircle2 size={13}/>{paidEnabled ? "Betaalde bronnen aan" : "Gratis bronnen actief"}</span></header>
    <section className="stats"><Metric icon={<ServerCog size={18}/>} label="Actieve jobs" value={activeJobs} meta={`${failed} mislukt`}/><Metric icon={<Gauge size={18}/>} label="Places vandaag" value={googleToday} meta={`Limiet ${dailyLimit}`}/><Metric label="Places deze maand" value={googleMonth} meta={`Limiet ${monthlyLimit}`}/><Metric icon={<AlertTriangle size={18}/>} label="Gefilterde leads" value={filtered} meta="Historie blijft bewaard"/></section>
    <div className="grid-two"><section className="card card-pad"><h2>Dekkingsgraad</h2><Coverage label="Nederland" data={nl}/><Coverage label="België" data={be}/><hr/><div className="definition"><dt>Bedrijven zonder website</dt><dd>{numberFormatter.format(noWebsite)}</dd></div><div className="definition"><dt>Websitekansen</dt><dd>{numberFormatter.format(websiteOpportunities)}</dd></div></section><section className="card card-pad"><h2>Kostenbeheersing</h2><p className="small muted">OpenStreetMap/Overpass is primair en gratis. Google Places en PageSpeed staan standaard uit.</p><Budget label="Google Places dagbudget" used={googleToday} limit={dailyLimit}/><Budget label="Google Places maandbudget" used={googleMonth} limit={monthlyLimit}/><Budget label="PageSpeed dagbudget" used={pagespeedToday} limit={Number(process.env.PAGESPEED_DAILY_LIMIT ?? 25)}/><p className="small muted">Betaalde providers: <strong>{paidEnabled ? "ingeschakeld" : "uitgeschakeld"}</strong>. Geschatte runkosten staan hieronder; werkelijke facturatie blijft leidend.</p></section></div>
    <CategoryManager categories={categories} excluded={excluded}/>
    <section className="card table-card admin-section"><div className="card-pad"><h2>Recente zoekruns</h2></div><div className="table-scroll"><table><thead><tr><th>Status</th><th>Gevonden</th><th>Gecontroleerd</th><th>Opgeslagen</th><th>Duplicaten</th><th>Bronfouten</th><th>Schatting</th><th>Gestart</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id}><td><span className="badge">{statusLabels[run.status]}</span></td><td>{run.candidatesFound}</td><td>{run.candidatesChecked}</td><td>{run.stored}/{run.targetCount}</td><td>{run.duplicates}</td><td title={run.logs.map((log) => log.message).join("\n")}>{run.sourceFailures}</td><td>€ {(run.estimatedCostCents / 100).toFixed(2)}</td><td>{run.startedAt?.toLocaleString("nl-NL") ?? "—"}</td></tr>)}</tbody></table></div></section>
    <section className="card table-card admin-section"><div className="card-pad"><h2>Recente scanjobs</h2></div>{jobs.length ? <div className="table-scroll"><table><thead><tr><th>Type</th><th>Gebied / lead</th><th>Status</th><th>API</th><th>Gevonden</th><th>Opgeslagen</th><th>Gestart</th><th>Fout</th><th></th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td>{job.type}</td><td>{job.coverageArea?.city || job.leadId || "—"}</td><td><span className={`badge ${job.status === "COMPLETE" ? "badge-green" : job.status === "FAILED" ? "badge-amber" : "badge-blue"}`}>{statusLabels[job.status]}</span></td><td>{job.apiCallsUsed}</td><td>{job.recordsFound}</td><td>{job.recordsStored}</td><td>{job.startedAt?.toLocaleString("nl-NL") || "—"}</td><td className="small">{job.errorMessage || "—"}</td><td>{job.status === "FAILED" && <RetryJobButton id={job.id}/>}</td></tr>)}</tbody></table></div> : <div className="empty"><strong>Nog geen jobs</strong></div>}</section>
  </div>;
}
function Metric({ icon, label, value, meta }: { icon?: React.ReactNode; label: string; value: number; meta: string }) { return <div className="card stat"><div className="stat-head"><span className="stat-label">{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value">{numberFormatter.format(value)}</div><div className="stat-meta">{meta}</div></div>; }
function Coverage({ label, data }: { label: string; data: { total: number; done: number; pct: number } }) { return <div className="coverage"><div><strong>{label}</strong><span className="muted">{data.done} / {data.total} · {data.pct}%</span></div><div className="progress"><span style={{ width: `${data.pct}%` }}/></div></div>; }
function Budget({ label, used, limit }: { label: string; used: number; limit: number }) { return <div className="budget"><div><span>{label}</span><strong>{used} / {limit}</strong></div><div className="progress"><span style={{ width: `${Math.min(100, used / Math.max(1, limit) * 100)}%` }}/></div></div>; }
