BEGIN;

CREATE TYPE "LeadStatus_new" AS ENUM (
  'NEW',
  'VOICEMAIL',
  'CALL_BACK',
  'INTERESTED',
  'APPOINTMENT',
  'QUOTE_SENT',
  'CUSTOMER'
);

ALTER TABLE "Lead" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "Lead"
  ALTER COLUMN "status" TYPE "LeadStatus_new"
  USING (
    CASE "status"::text
      WHEN 'NEW' THEN 'NEW'
      WHEN 'NEEDS_REVIEW' THEN 'NEW'
      WHEN 'VERIFIED' THEN 'NEW'
      WHEN 'CALLED' THEN 'VOICEMAIL'
      WHEN 'NO_ANSWER' THEN 'VOICEMAIL'
      WHEN 'CALL_BACK' THEN 'CALL_BACK'
      WHEN 'INTERESTED' THEN 'INTERESTED'
      WHEN 'APPOINTMENT' THEN 'APPOINTMENT'
      WHEN 'QUOTE_SENT' THEN 'QUOTE_SENT'
      WHEN 'WON' THEN 'CUSTOMER'
      WHEN 'INVOICED' THEN 'CUSTOMER'
      WHEN 'LOST' THEN 'NEW'
      WHEN 'REJECTED' THEN 'NEW'
      WHEN 'HAS_WEBSITE' THEN 'NEW'
      WHEN 'PERMANENTLY_CLOSED' THEN 'NEW'
      WHEN 'DO_NOT_CONTACT' THEN 'NEW'
      WHEN 'FILTERED' THEN 'NEW'
      ELSE 'NEW'
    END
  )::"LeadStatus_new";

DROP TYPE "LeadStatus";
ALTER TYPE "LeadStatus_new" RENAME TO "LeadStatus";
ALTER TABLE "Lead" ALTER COLUMN "status" SET DEFAULT 'NEW';

COMMIT;
