import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, Mail, MapPin, Phone } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { dateFormatter, statusLabels } from "@/lib/format";
import { AnalyzeButton, LeadEditor, SuppressLeadButton } from "@/components/lead-actions";

export default async function LeadDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const lead = await prisma.lead.findUnique({ where: { id }, include: { websiteAnalyses: { orderBy: { createdAt: "desc" }, take: 1 }, leadNotes: { orderBy: { createdAt: "desc" }, take: 20, include: { user: { select: { name: true } } } } } });
  if (!lead) notFound();
  const analysis = lead.websiteAnalyses[0];
  const reasons = (analysis?.reasons as { code: string; label: string; weight: number }[] | undefined) ?? [{ code: "NO_WEBSITE", label: "Geen eigen website in de brongegevens", weight: lead.opportunityScore }];
  return <div className="content">
    <Link href="/leads" className="button button-secondary" style={{ marginBottom: 20 }}><ArrowLeft size={15}/>Terug naar leads</Link>
    <header className="page-head"><div><span className="eyebrow">{statusLabels[lead.leadType]}</span><h1>{lead.companyName}</h1><p className="muted">{lead.category.replaceAll("_", " ")} · {lead.city}, {lead.country}</p></div><div className="actions detail-actions"><a className="button button-secondary" href={lead.googleMapsUrl} target="_blank" rel="noreferrer"><MapPin size={15}/>Bronkaart <ExternalLink size={13}/></a>{lead.websiteUrl&&<a className="button button-secondary" href={lead.websiteUrl} target="_blank" rel="noreferrer">Website <ExternalLink size={13}/></a>}<AnalyzeButton leadId={lead.id} disabled={!lead.websiteUrl}/><SuppressLeadButton leadId={lead.id}/></div></header>
    <section className="stats"><Score label="Website-score" value={lead.opportunityScore} meta="0–29 bruikbaar · 30–59 verbeterbaar · 60–100 sterk verouderd"/><Score label="Confidence" value={lead.confidenceScore} meta={`${lead.confidenceLevel.toLowerCase()} · bron- en databetrouwbaarheid`}/><Score label="Mobiele score" value={analysis?.mobileScore??null} meta="Alleen wanneer PageSpeed bewust is ingeschakeld"/><Score label="Conversiekwaliteit" value={lead.conversionQualityScore} meta="Transparante signaalschatting"/></section>
    <div className="detail-grid"><div style={{ display: "grid", gap: 18 }}>
      <section className="card card-pad"><h2>Waarom is dit een kans?</h2><div className="reason-list">{reasons.map((reason)=><span className="badge badge-amber" key={reason.code}>{reason.label} <small>+{reason.weight}</small></span>)}</div>{analysis&&<dl style={{ marginTop: 18 }}><Row label="Bereikbaar">{analysis.isReachable?"Ja":"Nee"}</Row><Row label="HTTPS">{yesNo(analysis.hasHttps)}</Row><Row label="Mobiele viewport">{yesNo(analysis.hasViewportMeta)}</Row><Row label="Duidelijke call-to-action">{yesNo(analysis.hasClearCta)}</Row><Row label="Contactformulier">{yesNo(analysis.hasContactForm)}</Row><Row label="Kapotte links">{analysis.hasBrokenLinks?`${analysis.brokenLinkCount} in steekproef`:"Geen in steekproef"}</Row><Row label="Kapotte afbeeldingen">{analysis.hasBrokenImages?`${analysis.brokenImageCount} in steekproef`:"Geen in steekproef"}</Row><Row label="Verouderde techniek">{yesNo(analysis.hasLegacyTechnology)}</Row><Row label="Serverreactie">{analysis.loadTimeMs?`${analysis.loadTimeMs} ms`:"Niet beschikbaar"}</Row><Row label="Laatste analyse">{dateFormatter.format(analysis.createdAt)}</Row></dl>}</section>
      <section className="card card-pad"><h2>Bedrijfsgegevens</h2><dl><Row label="Contactpersoon">{lead.contactPersonName||"Niet beschikbaar"}</Row><Row label="Telefoon"><span style={{ fontWeight: 750 }}><Phone size={14} style={{ display: "inline", marginRight: 6 }}/>{lead.normalizedPhoneNumber}</span></Row><Row label="E-mail">{lead.email?<span><Mail size={14} style={{ display: "inline", marginRight: 6 }}/>{lead.email}</span>:"Niet beschikbaar"}</Row><Row label="Adres">{lead.streetAddress}</Row><Row label="Postcode en plaats">{lead.postalCode||"—"} {lead.city}</Row><Row label="Gemeente">{lead.municipality||"—"}</Row><Row label="Provincie / regio">{lead.province||"—"}</Row><Row label="Website">{lead.websiteUrl||"Geen eigen website gevonden"}</Row><Row label="Bedrijfsstatus"><span className={lead.businessStatus==="OPERATIONAL"?"badge badge-green":"badge badge-amber"}>{statusLabels[lead.businessStatus]}</span></Row><Row label="Bron">{statusLabels[lead.source]} · {lead.externalPlaceId}</Row><Row label="Gevonden">{dateFormatter.format(lead.firstDiscoveredAt)}</Row><Row label="Gecontroleerd">{dateFormatter.format(lead.lastVerifiedAt)}</Row></dl></section>
      <section className="card card-pad"><h2>Notitiegeschiedenis</h2>{lead.leadNotes.length?<div className="note-list">{lead.leadNotes.map((note)=><div key={note.id}><p>{note.content}</p><span className="small muted">{note.user.name} · {note.createdAt.toLocaleString("nl-NL")}</span></div>)}</div>:<p className="small muted">Nog geen notities toegevoegd.</p>}</section>
    </div><aside className="detail-sidebar"><section className="card card-pad"><h2>Pipeline</h2><p><span className={`badge ${lead.status==="INVOICED"?"badge-green":lead.status==="FILTERED"?"badge-amber":"badge-blue"}`}>{statusLabels[lead.status]}</span></p>{lead.filterReason&&<p className="small muted"><strong>Belangrijkste reden:</strong><br/>{lead.filterReason}</p>}<p className="small muted">Handmatige status en notities worden niet door hercontroles overschreven.</p></section><LeadEditor leadId={lead.id} status={lead.status} notes={lead.notes} filterReason={lead.filterReason}/></aside></div>
  </div>;
}
function Row({ label, children }: { label: string; children: React.ReactNode }) { return <div className="definition"><dt>{label}</dt><dd>{children}</dd></div>; }
function Score({ label, value, meta }: { label: string; value: number | null; meta: string }) { return <div className="card stat"><span className="stat-label">{label}</span><div className="stat-value">{value??"—"}{value!==null&&<small>/100</small>}</div><div className="stat-meta">{meta}</div></div>; }
function yesNo(value: boolean | null) { return value===null?"Niet beschikbaar":value?"Ja":"Nee"; }
