import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ExternalLink, Mail, Map, MapPin, MessageCircle, Phone } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { dateFormatter, statusLabels, websiteStatusLabels } from "@/lib/format";
import { getGoogleBusinessUrl } from "@/lib/leads/google-business-url";
import { toPipelineOptions } from "@/lib/leads/pipeline";
import { AnalyzeButton, LeadEditor, SuppressLeadButton, WebsiteReviewActions } from "@/components/lead-actions";

export default async function LeadDetailPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params;
  const [lead,stages]=await Promise.all([prisma.lead.findUnique({where:{id},include:{pipelineStage:true,websiteAnalyses:{orderBy:{createdAt:"desc"},take:1},leadNotes:{orderBy:{createdAt:"desc"},take:20,include:{user:{select:{name:true}}}},evidence:{orderBy:{checkedAt:"desc"},take:50},activities:{orderBy:{createdAt:"desc"},take:40},sourceRecords:{orderBy:{fetchedAt:"desc"},take:10}}}),prisma.pipelineStage.findMany({where:{isActive:true},orderBy:{position:"asc"}})]);
  if(!lead)notFound(); const analysis=lead.websiteAnalyses[0];
  return <div className="content"><Link href="/leads" className="button button-secondary back-button"><ArrowLeft size={15}/>Terug naar leads</Link><header className="page-head"><div><span className="eyebrow">{websiteStatusLabels[lead.websiteStatus]}</span><h1>{lead.companyName}</h1><p className="muted">{lead.category.replaceAll("_"," ")} · {lead.city}, {lead.country}</p></div><div className="actions detail-actions">{lead.normalizedPhoneNumber&&<><a className="button button-secondary" href={`tel:${lead.normalizedPhoneNumber}`}><Phone size={15}/>Bellen</a><a className="button button-secondary" href={`https://wa.me/${lead.normalizedPhoneNumber.replace(/\D/g,"")}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={15}/>WhatsApp</a></>}{lead.email&&<a className="button button-secondary" href={`mailto:${lead.email}`}><Mail size={15}/>E-mail</a>}<a className="button button-secondary" href={getGoogleBusinessUrl(lead)} target="_blank" rel="noopener noreferrer"><MapPin size={15}/>Google zoeken</a><a className="button button-secondary" href={lead.sourceUrl||lead.googleMapsUrl} target="_blank" rel="noopener noreferrer"><Map size={15}/>Bronkaart</a>{lead.websiteUrl&&<a className="button button-secondary" href={lead.websiteUrl} target="_blank" rel="noopener noreferrer">Website <ExternalLink size={13}/></a>}<AnalyzeButton leadId={lead.id} disabled={!lead.websiteUrl}/><SuppressLeadButton leadId={lead.id}/></div></header>
    <section className="stats"><Score label="Opportunity" value={lead.opportunityScore} meta="Technische en commerciële kans"/><Score label="Website-confidence" value={lead.websiteConfidence} meta="Uitlegbaar bewijs, geen lege-veld-gok"/><Score label="Datakwaliteit" value={lead.confidenceScore} meta={`${lead.confidenceLevel.toLowerCase()} · identiteit en contactdata`}/><Score label="Mobiele score" value={analysis?.mobileScore??null} meta="Alleen na lokale websiteanalyse"/></section>
    <div className="detail-grid"><div className="detail-main"><section className="card card-pad"><h2>Waarom is dit een kans?</h2><p>{lead.websiteStatusReason||"Handmatige controle nodig."}</p><div className="reason-list">{lead.evidence.map((item)=><span className="badge badge-amber" key={item.id}>{item.checkType}: {item.result} · {item.confidence}/100</span>)}</div>{lead.evidence.length===0&&<p className="small muted">Nog geen gestructureerd bewijs beschikbaar voor deze oudere lead.</p>}</section>
      <section className="card card-pad"><h2>Verificatiebewijs</h2>{lead.evidence.length?<div className="evidence-list">{lead.evidence.map((item)=><article key={item.id}><div><strong>{item.checkType}</strong><span className="badge">{item.result}</span></div><p>{item.shortExplanation}</p><span className="small muted">{dateFormatter.format(item.checkedAt)} · confidence {item.confidence}{item.evidenceUrl&&<> · <a className="text-link" href={item.evidenceUrl} target="_blank" rel="noopener noreferrer">bewijs openen</a></>}</span></article>)}</div>:<p className="muted">Geen bewijsregels beschikbaar.</p>}</section>
      <section className="card card-pad"><h2>Bedrijfsgegevens</h2><dl><Row label="Contactpersoon">{lead.contactPerson||lead.contactPersonName||"Niet beschikbaar"}</Row><Row label="Telefoon">{lead.normalizedPhoneNumber||"Niet beschikbaar"}</Row><Row label="E-mail">{lead.email||"Niet beschikbaar"}</Row><Row label="Adres">{lead.streetAddress}</Row><Row label="Postcode en plaats">{lead.postalCode||"—"} {lead.city}</Row><Row label="Gemeente">{lead.municipality||"—"}</Row><Row label="Provincie / regio">{lead.province||"—"}</Row><Row label="Website">{lead.websiteUrl||"Geen eigen website gevonden"}</Row><Row label="Website-status">{websiteStatusLabels[lead.websiteStatus]}</Row><Row label="Bedrijfsstatus"><span className="badge">{statusLabels[lead.businessStatus]}</span></Row><Row label="Bron">{statusLabels[lead.source]} · {lead.externalPlaceId}</Row><Row label="Bron opgehaald">{lead.sourceFetchedAt?dateFormatter.format(lead.sourceFetchedAt):"Onbekend"}</Row><Row label="Laatst gecontroleerd">{dateFormatter.format(lead.lastVerifiedAt)}</Row><Row label="Volgende opvolging">{lead.nextFollowUpAt?dateFormatter.format(lead.nextFollowUpAt):"Niet gepland"}</Row></dl></section>
      <section className="card card-pad"><h2>Notities</h2>{lead.leadNotes.length?<div className="note-list">{lead.leadNotes.map((note)=><div key={note.id}><p>{note.content}</p><span className="small muted">{note.user.name} · {note.createdAt.toLocaleString("nl-NL")}</span></div>)}</div>:<p className="small muted">Nog geen notities toegevoegd.</p>}</section>
      <section className="card card-pad"><h2>Activiteit</h2>{lead.activities.length?<ol className="timeline">{lead.activities.map((activity)=><li key={activity.id}><strong>{activity.summary}</strong><div className="small muted">{activity.type} · {activity.createdAt.toLocaleString("nl-NL")}</div></li>)}</ol>:<p className="small muted">Nog geen activiteiten vastgelegd.</p>}</section></div>
      <aside className="detail-sidebar"><section className="card card-pad"><h2>Pipeline</h2><p><span className="badge badge-blue">{lead.pipelineStage.name}</span></p>{lead.filterReason&&<p className="small muted"><strong>Reden:</strong><br/>{lead.filterReason}</p>}<p className="small muted">Handmatige status en notities worden niet door hercontroles overschreven.</p></section><WebsiteReviewActions leadId={lead.id} googleUrl={getGoogleBusinessUrl(lead)} currentWebsite={lead.websiteUrl}/><LeadEditor leadId={lead.id} stageSlug={lead.pipelineStage.slug} stages={toPipelineOptions(stages)} notes={lead.notes} filterReason={lead.filterReason}/><section className="card card-pad"><h2>Bronrecords</h2>{lead.sourceRecords.map((record)=><p className="small" key={record.id}><strong>{record.source}</strong><br/><span className="muted">{record.sourceRecordId} · {dateFormatter.format(record.fetchedAt)}</span></p>)}</section></aside></div></div>;
}
function Row({label,children}:{label:string;children:React.ReactNode}){return <div className="definition"><dt>{label}</dt><dd>{children}</dd></div>;}
function Score({label,value,meta}:{label:string;value:number|null;meta:string}){return <div className="card stat"><span className="stat-label">{label}</span><div className="stat-value">{value??"—"}{value!==null&&<small>/100</small>}</div><div className="stat-meta">{meta}</div></div>;}
